version: '2.2'
services:
  monitorelastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: monitorelastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/monitorelastic/data
    ports:
      - 9201:9201
    networks:
      - monitornet
  monitorelastic2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: monitorelastic2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/monitorelastic/data
    networks:
      - monitornet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  monitornet:
